### ISSUE TITLE
Equations/Diffusion_Equation/model

### ISSUE THREAD

**Issue by MrDionisio** [favead/Spbstu_PMF#8]
Описать класс сети с заданием слоёв из конфига, на вход вектор размерности 2, на выход - 1

config = {
  'layers': [(2, 20), (20, 10), (10, 1)]
}

lin_layers = []
for layer in layers:
	lin_layers.append(nn.Linear(layer[0], layer[1]))
	lin_layers.append(nn.Tanh())
self.linears = nn.Sequential(*lin_layers)

forward:
	out1 = self.linears(x)

**Comment by favead** [comment]
Выполнено
